units metal
dimension 3
newton on
# processor
boundary m m p
atom_style atomic
# atom_modify
box tilt large
timestep 0.001

variable nthermo equal 1e3
#---------------------------------------------
# Potential info
#---------------------------------------------
# shell echo 'variable lmp_t_dir string REPLACE_LMP_TEMP_DIR ' > local_home_dir.mod
# include local_home_dir.mod
variable lmp_t_dir string REPLACE_LMP_TEMP_DIR
variable pot_id string REPLACE_POT_ID
variable pot_element_path string REPLACE_POT_ELEMENT_PATH
variable pot_prefix string ${lmp_t_dir}/potential/${pot_element_path}/${pot_id}
variable atom_type_seed equal REPLACE_ATOM_TYPE_SEED
variable atom_type string REPLACE_ATOM_TYPE
variable nt_atom equal REPLACE_NT_ATOM

variable calc_name string REPLACE_CALC_NAME
variable calc_id string ${calc_name}.${atom_type}.${pot_id}
include ${lmp_t_dir}/module/sys.mod # define: lmp_version, calc_host, start_time
include ${calc_id}_calc_info.mod # generated by sys.mod; define: calc_host start_time complete_time
include atomic_composition.mod # generated by run.sh; define change_atom, atomic_composition_notation, lat_para_file_exist

variable pot_rc equal REPLACE_POT_RC
#---------------------------------------------
# generate structure
#---------------------------------------------
# variable originx equal "0"
# variable originy equal "0"

variable xtal_structure string REPLACE_XTAL_STRUCTURE
variable c1 string REPLACE_C1
variable c2 string REPLACE_C2
variable c3 string REPLACE_C3
variable orientation string ${c1}_${c2}_${c3}

variable supercell_lx equal REPLACE_SUPERCELL_LX
variable supercell_ly equal REPLACE_SUPERCELL_LY
variable supercell_nz equal REPLACE_SUPERCELL_NZ

variable crack_type string REPLACE_CRACK_TYPE
variable crack_nheight equal REPLACE_CRACK_NHEIGHT
variable cancel_nheight equal REPLACE_CANCEL_NHEIGHT

variable plane_normal1 string REPLACE_PLANE_NORMAL1
variable plane_normal2 string REPLACE_PLANE_NORMAL2

variable frac_c1 equal REPLACE_FRAC_C1
variable frac_c2 equal REPLACE_FRAC_C2

variable inclined_cancel equal REPLACE_INCLINED_CANCEL
#---------------------------------------------
# K loading
#---------------------------------------------
variable KII0 equal REPLACE_KII0
variable KI0 equal REPLACE_KI0
variable KIII0 equal REPLACE_KIII0

variable dKII equal REPLACE_DKII0
variable dKI equal REPLACE_DKI0
variable dKIII equal REPLACE_DKIII0
variable k_load_step equal REPLACE_K_LOAD_STEP

variable is_relaxed equal REPLACE_IS_RELAXED
variable restart_fname string REPLACE_RESTART_FNAME

variable stroh_tensor_fname string "./data/stroh_tensor.dat"

variable full_elastic equal REPLACE_FULL_ELASTIC
#---------------------------------------------
# Minimization setting
#---------------------------------------------
variable conv_energy_tol equal REPLACE_CONV_ENERGY_TOL
variable conv_force_tol equal REPLACE_CONV_FORCE_TOL
variable max_iter equal REPLACE_MAX_ITER
variable max_eval equal REPLACE_MAX_EVAL

variable opt_loop_size equal REPLACE_OPT_LOOP_SIZE

variable fmax_tol equal REPLACE_FMAX_TOL
variable fmax equal 'fmax'
variable fnorm equal 'fnorm'
variable step equal 'step'

#---------------------------------------------
# some variables
#---------------------------------------------
variable vol equal vol
variable atoms equal atoms
